version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8080:8080
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - NODEJS_SERVER_ADDR_FE=nodejs:3000
      - NODEJS_SERVER_ADDR_BE=nodejs:5000
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - nodejs
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs